/* KNOWN SOURCE RULES: Group 2 CTLM/CMC use 4980 before 4309 and 4669;
   ORANGE BUSINESS booked uses 664 before 655; PORTABILITY uses 565 before 550.
   These branches are unreachable. Retained pending approved thresholds.
   tools/audit_deciles.py reports this as an unresolved model configuration. */
%put WARNING: SM_CHECK: Four decile chains are nonmonotonic. See tools/audit_deciles.py.;

data sm_tmp.demand_prf_char(compress=&sm_compress)
     sm_tmp.sm_score_lookup_input(compress=&sm_compress
        keep=authorization_id company mis_date ext_business_name ML_SCORE_P0
             product_type_1 product_type_2 product_type_3)
     sm_tmp.sm_app_index(keep=company authorization_id account_id mis_date status_name);
	format ML_score_P0 ML_score_P1 32.16;
	set sm_tmp.sm_characteristics_v;

	ML_score_P0 = ZRF1SCORE/1E16;
	ML_score_P1 = 1-ZRF1SCORE/1E16;

	IF a_business_name = 'Score Distribution - Group 2 CTLM' THEN
		DO;
			IF ZXNOTA = . 		  THEN A_DECILE_DEMAND = .;
			ELSE IF ZXNOTA <=2341 THEN A_DECILE_DEMAND = 1;
			ELSE IF ZXNOTA <=2756 THEN A_DECILE_DEMAND = 2;
			ELSE IF ZXNOTA <=3106 THEN A_DECILE_DEMAND = 3;
			ELSE IF ZXNOTA <=3382 THEN A_DECILE_DEMAND = 4;
			ELSE IF ZXNOTA <=3734 THEN A_DECILE_DEMAND = 5;
			ELSE IF ZXNOTA <=4980 THEN A_DECILE_DEMAND = 6;
			ELSE IF ZXNOTA <=4309 THEN A_DECILE_DEMAND = 7;
			ELSE IF ZXNOTA <=4669 THEN A_DECILE_DEMAND = 8;
			ELSE IF ZXNOTA <=5106 THEN A_DECILE_DEMAND = 9;
			ELSE IF ZXNOTA <=9999 THEN A_DECILE_DEMAND = 10;
		END;
	ELSE IF a_business_name = 'Score Distribution - Group 2 CMC' THEN
		DO;
			IF ZXNOTA = . 		  THEN A_DECILE_DEMAND = .;
			ELSE IF ZXNOTA <=2341 THEN A_DECILE_DEMAND = 1;
			ELSE IF ZXNOTA <=2756 THEN A_DECILE_DEMAND = 2;
			ELSE IF ZXNOTA <=3106 THEN A_DECILE_DEMAND = 3;
			ELSE IF ZXNOTA <=3382 THEN A_DECILE_DEMAND = 4;
			ELSE IF ZXNOTA <=3734 THEN A_DECILE_DEMAND = 5;
			ELSE IF ZXNOTA <=4980 THEN A_DECILE_DEMAND = 6;
			ELSE IF ZXNOTA <=4309 THEN A_DECILE_DEMAND = 7;
			ELSE IF ZXNOTA <=4669 THEN A_DECILE_DEMAND = 8;
			ELSE IF ZXNOTA <=5106 THEN A_DECILE_DEMAND = 9;
			ELSE IF ZXNOTA <=9999 THEN A_DECILE_DEMAND = 10;
		END;
	ELSE IF a_business_name = 'Score Auto Moto CTLM' THEN
		DO;
			IF ZXNOTA = . 		  THEN A_DECILE_DEMAND = .;
			ELSE IF ZXNOTA <29629 THEN A_DECILE_DEMAND = 1;
			ELSE IF ZXNOTA <33524 THEN A_DECILE_DEMAND = 2;
			ELSE IF ZXNOTA <36510 THEN A_DECILE_DEMAND = 3;
			ELSE IF ZXNOTA <39494 THEN A_DECILE_DEMAND = 4;
			ELSE IF ZXNOTA <42083 THEN A_DECILE_DEMAND = 5;
			ELSE IF ZXNOTA <44681 THEN A_DECILE_DEMAND = 6;
			ELSE IF ZXNOTA <47419 THEN A_DECILE_DEMAND = 7;
			ELSE IF ZXNOTA <50764 THEN A_DECILE_DEMAND = 8;
			ELSE IF ZXNOTA <55555 THEN A_DECILE_DEMAND = 9;
			ELSE IF ZXNOTA <99999 THEN A_DECILE_DEMAND = 10;

			IF ZXNOTA = . 		  THEN A_DECILE_BOOKED_F = .;
			ELSE IF ZXNOTA <32839 THEN A_DECILE_BOOKED_F = 1;
			ELSE IF ZXNOTA <37155 THEN A_DECILE_BOOKED_F = 2;
			ELSE IF ZXNOTA <39895 THEN A_DECILE_BOOKED_F = 3;
			ELSE IF ZXNOTA <42600 THEN A_DECILE_BOOKED_F = 4;
			ELSE IF ZXNOTA <45206 THEN A_DECILE_BOOKED_F = 5;
			ELSE IF ZXNOTA <47705 THEN A_DECILE_BOOKED_F = 6;
			ELSE IF ZXNOTA <50082 THEN A_DECILE_BOOKED_F = 7;
			ELSE IF ZXNOTA <53278 THEN A_DECILE_BOOKED_F = 8;
			ELSE IF ZXNOTA <56870 THEN A_DECILE_BOOKED_F = 9;
			ELSE IF ZXNOTA <99999 THEN A_DECILE_BOOKED_F = 10;

		END;
	ELSE IF a_business_name = 'Score Cards Retail E-COMM CTLM' THEN
		DO;
			IF ZXNOTA = . 		  THEN A_DECILE_DEMAND = .;
			ELSE IF ZXNOTA <=3154 THEN A_DECILE_DEMAND = 1;
			ELSE IF ZXNOTA <=3573 THEN A_DECILE_DEMAND = 2;
			ELSE IF ZXNOTA <=3963 THEN A_DECILE_DEMAND = 3;
			ELSE IF ZXNOTA <=4273 THEN A_DECILE_DEMAND = 4;
			ELSE IF ZXNOTA <=4544 THEN A_DECILE_DEMAND = 5;
			ELSE IF ZXNOTA <=4816 THEN A_DECILE_DEMAND = 6;
			ELSE IF ZXNOTA <=5119 THEN A_DECILE_DEMAND = 7;
			ELSE IF ZXNOTA <=5381 THEN A_DECILE_DEMAND = 8;
			ELSE IF ZXNOTA <=5671 THEN A_DECILE_DEMAND = 9;
			ELSE IF ZXNOTA <=9999 THEN A_DECILE_DEMAND = 10;
		END;
	ELSE IF a_business_name = 'Score Cards Retail E-COMM CMC' THEN
		DO;
			IF ZXNOTA = . 		  THEN A_DECILE_DEMAND = .;
			ELSE IF ZXNOTA <=3154 THEN A_DECILE_DEMAND = 1;
			ELSE IF ZXNOTA <=3573 THEN A_DECILE_DEMAND = 2;
			ELSE IF ZXNOTA <=3963 THEN A_DECILE_DEMAND = 3;
			ELSE IF ZXNOTA <=4273 THEN A_DECILE_DEMAND = 4;
			ELSE IF ZXNOTA <=4544 THEN A_DECILE_DEMAND = 5;
			ELSE IF ZXNOTA <=4816 THEN A_DECILE_DEMAND = 6;
			ELSE IF ZXNOTA <=5119 THEN A_DECILE_DEMAND = 7;
			ELSE IF ZXNOTA <=5381 THEN A_DECILE_DEMAND = 8;
			ELSE IF ZXNOTA <=5671 THEN A_DECILE_DEMAND = 9;
			ELSE IF ZXNOTA <=9999 THEN A_DECILE_DEMAND = 10;
		END;
	ELSE IF a_business_name = 'Score Distribution 2013 - Group 1 CTLM' THEN
		DO;
			IF ZXNOTA = . 		  THEN A_DECILE_DEMAND = .;
			ELSE IF ZXNOTA <=2614 THEN A_DECILE_DEMAND = 1;
			ELSE IF ZXNOTA <=3230 THEN A_DECILE_DEMAND = 2;
			ELSE IF ZXNOTA <=3673 THEN A_DECILE_DEMAND = 3;
			ELSE IF ZXNOTA <=4039 THEN A_DECILE_DEMAND = 4;
			ELSE IF ZXNOTA <=4378 THEN A_DECILE_DEMAND = 5;
			ELSE IF ZXNOTA <=4719 THEN A_DECILE_DEMAND = 6;
			ELSE IF ZXNOTA <=4987 THEN A_DECILE_DEMAND = 7;
			ELSE IF ZXNOTA <=5381 THEN A_DECILE_DEMAND = 8;
			ELSE IF ZXNOTA <=5834 THEN A_DECILE_DEMAND = 9;
			ELSE IF ZXNOTA <=9999 THEN A_DECILE_DEMAND = 10;
		END;
	ELSE IF a_business_name = 'Score Distribution 2013 - Group 1 CMC' THEN
		DO;
			IF ZXNOTA = . 		  THEN A_DECILE_DEMAND = .;
			ELSE IF ZXNOTA <=2614 THEN A_DECILE_DEMAND = 1;
			ELSE IF ZXNOTA <=3230 THEN A_DECILE_DEMAND = 2;
			ELSE IF ZXNOTA <=3673 THEN A_DECILE_DEMAND = 3;
			ELSE IF ZXNOTA <=4039 THEN A_DECILE_DEMAND = 4;
			ELSE IF ZXNOTA <=4378 THEN A_DECILE_DEMAND = 5;
			ELSE IF ZXNOTA <=4719 THEN A_DECILE_DEMAND = 6;
			ELSE IF ZXNOTA <=4987 THEN A_DECILE_DEMAND = 7;
			ELSE IF ZXNOTA <=5381 THEN A_DECILE_DEMAND = 8;
			ELSE IF ZXNOTA <=5834 THEN A_DECILE_DEMAND = 9;
			ELSE IF ZXNOTA <=9999 THEN A_DECILE_DEMAND = 10;
		END;
	ELSE IF a_business_name = 'A-Score DIRECT' THEN
		DO;
			IF ZXNOTA = . 		 THEN A_DECILE_DEMAND = .;
			ELSE IF ZXNOTA <=342  THEN A_DECILE_DEMAND = 1;
			ELSE IF ZXNOTA <=352  THEN A_DECILE_DEMAND = 2;
			ELSE IF ZXNOTA <=359  THEN A_DECILE_DEMAND = 3;
			ELSE IF ZXNOTA <=368  THEN A_DECILE_DEMAND = 4;
			ELSE IF ZXNOTA <=376  THEN A_DECILE_DEMAND = 5;
			ELSE IF ZXNOTA <=387  THEN A_DECILE_DEMAND = 6;
			ELSE IF ZXNOTA <=397  THEN A_DECILE_DEMAND = 7;
			ELSE IF ZXNOTA <=410  THEN A_DECILE_DEMAND = 8;
			ELSE IF ZXNOTA <=428  THEN A_DECILE_DEMAND = 9;
			ELSE IF ZXNOTA <=9999 THEN A_DECILE_DEMAND = 10;

			IF ZXNOTA = . 		THEN A_DECILE_BOOKED_F = .;
			ELSE IF ZXNOTA <=362  THEN A_DECILE_BOOKED_F = 1;
			ELSE IF ZXNOTA <=373  THEN A_DECILE_BOOKED_F = 2;
			ELSE IF ZXNOTA <=384  THEN A_DECILE_BOOKED_F = 3;
			ELSE IF ZXNOTA <=394  THEN A_DECILE_BOOKED_F = 4;
			ELSE IF ZXNOTA <=402  THEN A_DECILE_BOOKED_F = 5;
			ELSE IF ZXNOTA <=412  THEN A_DECILE_BOOKED_F = 6;
			ELSE IF ZXNOTA <=421  THEN A_DECILE_BOOKED_F = 7;
			ELSE IF ZXNOTA <=431  THEN A_DECILE_BOOKED_F = 8;
			ELSE IF ZXNOTA <=449  THEN A_DECILE_BOOKED_F = 9;
			ELSE IF ZXNOTA <=9999 THEN A_DECILE_BOOKED_F = 10;
		END;
	ELSE IF a_business_name = 'A-Score DIRECT XFR' THEN
		DO;
			IF zxnota = . 		 THEN A_DECILE_BOOKED_F = .;
			ELSE IF zxnota <364  THEN A_DECILE_BOOKED_F = 1;
			ELSE IF zxnota <377  THEN A_DECILE_BOOKED_F = 2;
			ELSE IF zxnota <380  THEN A_DECILE_BOOKED_F = 3;
			ELSE IF zxnota <382  THEN A_DECILE_BOOKED_F = 4;
			ELSE IF zxnota <388  THEN A_DECILE_BOOKED_F = 5;
			ELSE IF zxnota <390  THEN A_DECILE_BOOKED_F = 6;
			ELSE IF zxnota <396  THEN A_DECILE_BOOKED_F = 7;
			ELSE IF zxnota <400  THEN A_DECILE_BOOKED_F = 8;
			ELSE IF zxnota <410  THEN A_DECILE_BOOKED_F = 9;
			ELSE IF zxnota <9999 THEN A_DECILE_BOOKED_F = 10;	

			IF zxnota = . 	   THEN A_DECILE_DEMAND = .;
			ELSE IF zxnota <335  THEN A_DECILE_DEMAND = 1;
			ELSE IF zxnota <344  THEN A_DECILE_DEMAND = 2;
			ELSE IF zxnota <353  THEN A_DECILE_DEMAND = 3;
			ELSE IF zxnota <354  THEN A_DECILE_DEMAND = 4;
			ELSE IF zxnota <363  THEN A_DECILE_DEMAND = 5;
			ELSE IF zxnota <369  THEN A_DECILE_DEMAND = 6;
			ELSE IF zxnota <374  THEN A_DECILE_DEMAND = 7;
			ELSE IF zxnota <382  THEN A_DECILE_DEMAND = 8;
			ELSE IF zxnota <392  THEN A_DECILE_DEMAND = 9;
			ELSE IF zxnota <9999 THEN A_DECILE_DEMAND = 10;			
		END;
	ELSE IF a_business_name = 'A-Score DIRECT ML CMC' THEN
		DO;

			if ZXNOTA >9999 then 
				do;
					ML_score_P0 = ZXNOTA/1E16;
					ML_score_P1 = 1-ZXNOTA/1E16;
			end;

			IF 		ML_SCORE_P0 = . 		   THEN A_DECILE_DEMAND = .;
			ELSE IF ML_SCORE_P0 >=0.9958574392 THEN A_DECILE_DEMAND = 10;
			ELSE IF ML_SCORE_P0 >=0.9923491004 THEN A_DECILE_DEMAND = 9;
			ELSE IF ML_SCORE_P0 >=0.9884817660 THEN A_DECILE_DEMAND = 8;
			ELSE IF ML_SCORE_P0 >=0.9843352199 THEN A_DECILE_DEMAND = 7;
			ELSE IF ML_SCORE_P0 >=0.9785961345 THEN A_DECILE_DEMAND = 6;
			ELSE IF ML_SCORE_P0 >=0.9716936258 THEN A_DECILE_DEMAND = 5;
			ELSE IF ML_SCORE_P0 >=0.9665177813 THEN A_DECILE_DEMAND = 4;
			ELSE IF ML_SCORE_P0 >=0.9629992184 THEN A_DECILE_DEMAND = 3;
			ELSE IF ML_SCORE_P0 >=0.9538579450 THEN A_DECILE_DEMAND = 2;
			ELSE IF ML_SCORE_P0 >=0 		   THEN A_DECILE_DEMAND = 1;

			IF 		ML_SCORE_P0 = . 		 THEN A_DECILE_BOOKED_F = .;
			ELSE IF ML_SCORE_P0 >=0.99697480 THEN A_DECILE_BOOKED_F = 10;
			ELSE IF ML_SCORE_P0 >=0.99477936 THEN A_DECILE_BOOKED_F = 9;
			ELSE IF ML_SCORE_P0 >=0.99227312 THEN A_DECILE_BOOKED_F = 8;
			ELSE IF ML_SCORE_P0 >=0.98944254 THEN A_DECILE_BOOKED_F = 7;
			ELSE IF ML_SCORE_P0 >=0.98611704 THEN A_DECILE_BOOKED_F = 6; 
			ELSE IF ML_SCORE_P0 >=0.98175432 THEN A_DECILE_BOOKED_F = 5;
			ELSE IF ML_SCORE_P0 >=0.97614300 THEN A_DECILE_BOOKED_F = 4;
			ELSE IF ML_SCORE_P0 >=0.96765843 THEN A_DECILE_BOOKED_F = 3;
			ELSE IF ML_SCORE_P0 >=0.95318483 THEN A_DECILE_BOOKED_F = 2;
			ELSE IF ML_SCORE_P0 >=0 		 THEN A_DECILE_BOOKED_F = 1;
		END;
	ELSE IF a_business_name = 'A-Score DISTRIB Retail Traditional CTLM' THEN
		DO;
			if zvers < 20260219 then 
				do;
					ML_score_P0 = ZRF1SCORE/1E16;
					ML_score_P1 = 1-ZRF1SCORE/1E16;
				end;
			else 
				do;
					ML_score_P0 = zxnota/1E12;
					ML_score_P1 = 1-zxnota/1E12;
				end;	

			IF 		ML_SCORE_P0 = . 		 THEN A_DECILE_DEMAND = .;
			ELSE IF ML_SCORE_P0 >=0.99645586 THEN A_DECILE_DEMAND = 10;
			ELSE IF ML_SCORE_P0 >=0.99366430 THEN A_DECILE_DEMAND = 9;
			ELSE IF ML_SCORE_P0 >=0.99056554 THEN A_DECILE_DEMAND = 8;
			ELSE IF ML_SCORE_P0 >=0.98713138 THEN A_DECILE_DEMAND = 7;
			ELSE IF ML_SCORE_P0 >=0.98297046 THEN A_DECILE_DEMAND = 6; 
			ELSE IF ML_SCORE_P0 >=0.97775843 THEN A_DECILE_DEMAND = 5;
			ELSE IF ML_SCORE_P0 >=0.97088151 THEN A_DECILE_DEMAND = 4;
			ELSE IF ML_SCORE_P0 >=0.96109812 THEN A_DECILE_DEMAND = 3;
			ELSE IF ML_SCORE_P0 >=0.94600967 THEN A_DECILE_DEMAND = 2;
			ELSE IF ML_SCORE_P0 >=0 		 THEN A_DECILE_DEMAND = 1;

			IF 		ML_SCORE_P0 = . 		 THEN A_DECILE_BOOKED_F = .;
			ELSE IF ML_SCORE_P0 >=0.99697480 THEN A_DECILE_BOOKED_F = 10;
			ELSE IF ML_SCORE_P0 >=0.99477936 THEN A_DECILE_BOOKED_F = 9;
			ELSE IF ML_SCORE_P0 >=0.99227312 THEN A_DECILE_BOOKED_F = 8;
			ELSE IF ML_SCORE_P0 >=0.98944254 THEN A_DECILE_BOOKED_F = 7;
			ELSE IF ML_SCORE_P0 >=0.98611704 THEN A_DECILE_BOOKED_F = 6; 
			ELSE IF ML_SCORE_P0 >=0.98175432 THEN A_DECILE_BOOKED_F = 5;
			ELSE IF ML_SCORE_P0 >=0.97614300 THEN A_DECILE_BOOKED_F = 4;
			ELSE IF ML_SCORE_P0 >=0.96765843 THEN A_DECILE_BOOKED_F = 3;
			ELSE IF ML_SCORE_P0 >=0.95318483 THEN A_DECILE_BOOKED_F = 2;
			ELSE IF ML_SCORE_P0 >=0 		 THEN A_DECILE_BOOKED_F = 1;
		END;
	ELSE IF a_business_name = 'A-Score DISTRIB Retail Traditional CMC' THEN
		DO;		
			if ZXNOTA >9999 then 
				do;
					ML_score_P0 = ZXNOTA/1E16;
					ML_score_P1 = 1-ZXNOTA/1E16;
				end;
	
			IF 		ML_SCORE_P0 = . 		   THEN A_DECILE_BOOKED_F = .;
			ELSE IF ML_SCORE_P0 < 0.9597980398 THEN A_DECILE_BOOKED_F = 1;
			ELSE IF ML_SCORE_P0 < 0.9730817112 THEN A_DECILE_BOOKED_F = 2;
			ELSE IF ML_SCORE_P0 < 0.9799053712 THEN A_DECILE_BOOKED_F = 3;
			ELSE IF ML_SCORE_P0 < 0.9845110076 THEN A_DECILE_BOOKED_F = 4;
			ELSE IF ML_SCORE_P0 < 0.9877153775 THEN A_DECILE_BOOKED_F = 5;
			ELSE IF ML_SCORE_P0 < 0.9905629245 THEN A_DECILE_BOOKED_F = 6;
			ELSE IF ML_SCORE_P0 < 0.9930060064 THEN A_DECILE_BOOKED_F = 7;
			ELSE IF ML_SCORE_P0 < 0.9951444508 THEN A_DECILE_BOOKED_F = 8;
			ELSE IF ML_SCORE_P0 < 0.9971201596 THEN A_DECILE_BOOKED_F = 9;
			ELSE IF ML_SCORE_P0 <=1 		   THEN A_DECILE_BOOKED_F = 10;	

			IF 		ML_SCORE_P0 = . 		   THEN A_DECILE_DEMAND = .;
			ELSE IF ML_SCORE_P0 < 0.9507690000 THEN A_DECILE_DEMAND = 1;
			ELSE IF ML_SCORE_P0 < 0.9639239000 THEN A_DECILE_DEMAND = 2;
			ELSE IF ML_SCORE_P0 < 0.9737775000 THEN A_DECILE_DEMAND = 3;
			ELSE IF ML_SCORE_P0 < 0.9800660000 THEN A_DECILE_DEMAND = 4;
			ELSE IF ML_SCORE_P0 < 0.9844733000 THEN A_DECILE_DEMAND = 5;
			ELSE IF ML_SCORE_P0 < 0.9878164000 THEN A_DECILE_DEMAND = 6;
			ELSE IF ML_SCORE_P0 < 0.9910582000 THEN A_DECILE_DEMAND = 7;
			ELSE IF ML_SCORE_P0 < 0.9939203000 THEN A_DECILE_DEMAND = 8;
			ELSE IF ML_SCORE_P0 < 0.9965739000 THEN A_DECILE_DEMAND = 9;
			ELSE IF ML_SCORE_P0 <=1 		 THEN   A_DECILE_DEMAND = 10;			

		END;

	IF EXT_business_name = 'Equifax Risk Score - Direct CTLM' THEN
		DO;
			IF SCRPLUST1 < 0 OR SCRPLUST1 = . 	THEN EXT_DECILE_BOOKED_F = .;
			ELSE IF SCRPLUST1 > 17 				THEN EXT_DECILE_BOOKED_F = 1;
			ELSE IF SCRPLUST1 > 13 				THEN EXT_DECILE_BOOKED_F = 2;
			ELSE IF SCRPLUST1 > 12 				THEN EXT_DECILE_BOOKED_F = 3;
			ELSE IF SCRPLUST1 >	10				THEN EXT_DECILE_BOOKED_F = 4;
			ELSE IF SCRPLUST1 > 9 				THEN EXT_DECILE_BOOKED_F = 5;
			ELSE IF SCRPLUST1 > 7 				THEN EXT_DECILE_BOOKED_F = 6;
			ELSE IF SCRPLUST1 > 5 				THEN EXT_DECILE_BOOKED_F = 7;
			ELSE IF SCRPLUST1 > 4 				THEN EXT_DECILE_BOOKED_F = 8;
			ELSE IF SCRPLUST1 > 1 				THEN EXT_DECILE_BOOKED_F = 9;
			ELSE 							 		 EXT_DECILE_BOOKED_F = 10;

			IF SCRPLUST1 < 0 OR SCRPLUST1 = . 	THEN EXT_DECILE_DEMAND = .;
			ELSE IF SCRPLUST1 > 17 				THEN EXT_DECILE_DEMAND = 1;
			ELSE IF SCRPLUST1 > 13 				THEN EXT_DECILE_DEMAND = 2;
			ELSE IF SCRPLUST1 > 12 				THEN EXT_DECILE_DEMAND = 3;
			ELSE IF SCRPLUST1 >	10				THEN EXT_DECILE_DEMAND = 4;
			ELSE IF SCRPLUST1 > 9 				THEN EXT_DECILE_DEMAND = 5;
			ELSE IF SCRPLUST1 > 7 				THEN EXT_DECILE_DEMAND = 6;
			ELSE IF SCRPLUST1 > 5 				THEN EXT_DECILE_DEMAND = 7;
			ELSE IF SCRPLUST1 > 4 				THEN EXT_DECILE_DEMAND = 8;
			ELSE IF SCRPLUST1 > 1 				THEN EXT_DECILE_DEMAND = 9;
			ELSE 							 		 EXT_DECILE_DEMAND = 10;
		END;
	ELSE IF EXT_business_name = 'Equifax Risk Score Retail E-COMM CTLM' THEN
		DO;
			IF SCRPLUST1 < 0 OR SCRPLUST1 = . 	THEN EXT_DECILE_BOOKED_F = .;
			ELSE IF SCRPLUST1 > 17 				THEN EXT_DECILE_BOOKED_F = 1;
			ELSE IF SCRPLUST1 > 14 				THEN EXT_DECILE_BOOKED_F = 2;
			ELSE IF SCRPLUST1 > 12 				THEN EXT_DECILE_BOOKED_F = 3;
			ELSE IF SCRPLUST1 >	11				THEN EXT_DECILE_BOOKED_F = 4;
			ELSE IF SCRPLUST1 > 9 				THEN EXT_DECILE_BOOKED_F = 5;
			ELSE IF SCRPLUST1 > 7 				THEN EXT_DECILE_BOOKED_F = 6;
			ELSE IF SCRPLUST1 > 5 				THEN EXT_DECILE_BOOKED_F = 7;
			ELSE IF SCRPLUST1 > 4 				THEN EXT_DECILE_BOOKED_F = 8;
			ELSE IF SCRPLUST1 > 1 				THEN EXT_DECILE_BOOKED_F = 9;
			ELSE 									 EXT_DECILE_BOOKED_F = 10;

			IF SCRPLUST1 < 0 OR SCRPLUST1 = . 	THEN EXT_DECILE_DEMAND = .;
			ELSE IF SCRPLUST1 > 17 				THEN EXT_DECILE_DEMAND = 1;
			ELSE IF SCRPLUST1 > 14 				THEN EXT_DECILE_DEMAND = 2;
			ELSE IF SCRPLUST1 > 12 				THEN EXT_DECILE_DEMAND = 3;
			ELSE IF SCRPLUST1 >	11				THEN EXT_DECILE_DEMAND = 4;
			ELSE IF SCRPLUST1 > 9 				THEN EXT_DECILE_DEMAND = 5;
			ELSE IF SCRPLUST1 > 7 				THEN EXT_DECILE_DEMAND = 6;
			ELSE IF SCRPLUST1 > 5 				THEN EXT_DECILE_DEMAND = 7;
			ELSE IF SCRPLUST1 > 4 				THEN EXT_DECILE_DEMAND = 8;
			ELSE IF SCRPLUST1 > 1 				THEN EXT_DECILE_DEMAND = 9;
			ELSE 									 EXT_DECILE_DEMAND = 10;
		END;
	ELSE IF EXT_business_name = 'Equifax Risk Score - Direct CMC' THEN
		DO;
			IF SCRPLUST1 < 0 OR SCRPLUST1 = . 	THEN EXT_DECILE_BOOKED_F = .;
			ELSE IF SCRPLUST1 > 18 				THEN EXT_DECILE_BOOKED_F = 1;
			ELSE IF SCRPLUST1 > 14 				THEN EXT_DECILE_BOOKED_F = 2;
			ELSE IF SCRPLUST1 > 12 				THEN EXT_DECILE_BOOKED_F = 3;
			ELSE IF SCRPLUST1 >	10				THEN EXT_DECILE_BOOKED_F = 4;
			ELSE IF SCRPLUST1 > 9				THEN EXT_DECILE_BOOKED_F = 5;
			ELSE IF SCRPLUST1 > 7 				THEN EXT_DECILE_BOOKED_F = 6;
			ELSE IF SCRPLUST1 > 5 				THEN EXT_DECILE_BOOKED_F = 7;
			ELSE IF SCRPLUST1 > 3 				THEN EXT_DECILE_BOOKED_F = 8;
			ELSE IF SCRPLUST1 > 1 				THEN EXT_DECILE_BOOKED_F = 9;
			ELSE 							 		 EXT_DECILE_BOOKED_F = 10;

			IF SCRPLUST1 < 0 OR SCRPLUST1 = . 	THEN EXT_DECILE_DEMAND = .;
			ELSE IF SCRPLUST1 > 18 				THEN EXT_DECILE_DEMAND = 1;
			ELSE IF SCRPLUST1 > 16 				THEN EXT_DECILE_DEMAND = 2;
			ELSE IF SCRPLUST1 > 14 				THEN EXT_DECILE_DEMAND = 3;
			ELSE IF SCRPLUST1 >	12				THEN EXT_DECILE_DEMAND = 4;
			ELSE IF SCRPLUST1 > 10				THEN EXT_DECILE_DEMAND = 5;
			ELSE IF SCRPLUST1 > 8 				THEN EXT_DECILE_DEMAND = 6;
			ELSE IF SCRPLUST1 > 6 				THEN EXT_DECILE_DEMAND = 7;
			ELSE IF SCRPLUST1 > 4 				THEN EXT_DECILE_DEMAND = 8;
			ELSE IF SCRPLUST1 > 2 				THEN EXT_DECILE_DEMAND = 9;
			ELSE 							 		 EXT_DECILE_DEMAND = 10;
		END;
	ELSE IF EXT_business_name = 'Equifax Risk Score - Direct XFR' THEN
		DO;
			IF SCRPLUST1 < 0 OR SCRPLUST1 = . 	THEN EXT_DECILE_DEMAND = .;
			ELSE IF SCRPLUST1 > 19 				THEN EXT_DECILE_DEMAND = 1;
			ELSE IF SCRPLUST1 > 16 				THEN EXT_DECILE_DEMAND = 2;
			ELSE IF SCRPLUST1 > 13 				THEN EXT_DECILE_DEMAND = 3;
			ELSE IF SCRPLUST1 >	12				THEN EXT_DECILE_DEMAND = 4;
			ELSE IF SCRPLUST1 > 10 				THEN EXT_DECILE_DEMAND = 5;
			ELSE IF SCRPLUST1 > 9 				THEN EXT_DECILE_DEMAND = 6;
			ELSE IF SCRPLUST1 > 8 				THEN EXT_DECILE_DEMAND = 7;
			ELSE IF SCRPLUST1 > 7 				THEN EXT_DECILE_DEMAND = 8;
			ELSE IF SCRPLUST1 > 4 				THEN EXT_DECILE_DEMAND = 9;
			ELSE 							 		 EXT_DECILE_DEMAND = 10;

			IF SCRPLUST1 < 0 OR SCRPLUST1 = . 	THEN EXT_DECILE_BOOKED_F = .;
			ELSE IF SCRPLUST1 > 13 				THEN EXT_DECILE_BOOKED_F = 1;
			ELSE IF SCRPLUST1 > 12 				THEN EXT_DECILE_BOOKED_F = 2;
			ELSE IF SCRPLUST1 > 10 				THEN EXT_DECILE_BOOKED_F = 3;
			ELSE IF SCRPLUST1 >	9				THEN EXT_DECILE_BOOKED_F = 4;
			ELSE IF SCRPLUST1 > 7				THEN EXT_DECILE_BOOKED_F = 5;
			ELSE IF SCRPLUST1 > 6 				THEN EXT_DECILE_BOOKED_F = 6;
			ELSE IF SCRPLUST1 > 4 				THEN EXT_DECILE_BOOKED_F = 7;
			ELSE IF SCRPLUST1 > 3 				THEN EXT_DECILE_BOOKED_F = 8;
			ELSE IF SCRPLUST1 > 1 				THEN EXT_DECILE_BOOKED_F = 9;
			ELSE 							 		 EXT_DECILE_BOOKED_F = 10;
		END;

	IF B_business_name = 'SQE used for granting CTLM' THEN
		DO;
			IF int(NOTA) = . 		 THEN B_DECILE_DEMAND = .;
			ELSE IF int(NOTA) <3303  THEN B_DECILE_DEMAND = 1;
			ELSE IF int(NOTA) <3932  THEN B_DECILE_DEMAND = 2;
			ELSE IF int(NOTA) <4338  THEN B_DECILE_DEMAND = 3;
			ELSE IF int(NOTA) <4666  THEN B_DECILE_DEMAND = 4;
			ELSE IF int(NOTA) <4959  THEN B_DECILE_DEMAND = 5;
			ELSE IF int(NOTA) <5278  THEN B_DECILE_DEMAND = 6;
			ELSE IF int(NOTA) <5700  THEN B_DECILE_DEMAND = 7;
			ELSE IF int(NOTA) <6308  THEN B_DECILE_DEMAND = 8;
			ELSE IF int(NOTA) <7013  THEN B_DECILE_DEMAND = 9;
			ELSE IF int(NOTA) <100000   THEN B_DECILE_DEMAND = 10;

			IF int(NOTA) = . 		 THEN B_DECILE_BOOKED_F = .;
			ELSE IF int(NOTA) <4399  THEN B_DECILE_BOOKED_F = 1;
			ELSE IF int(NOTA) <4787  THEN B_DECILE_BOOKED_F = 2;
			ELSE IF int(NOTA) <5070  THEN B_DECILE_BOOKED_F = 3;
			ELSE IF int(NOTA) <5403  THEN B_DECILE_BOOKED_F = 4;
			ELSE IF int(NOTA) <5778  THEN B_DECILE_BOOKED_F = 5;
			ELSE IF int(NOTA) <6209  THEN B_DECILE_BOOKED_F = 6;
			ELSE IF int(NOTA) <6609  THEN B_DECILE_BOOKED_F = 7;
			ELSE IF int(NOTA) <7120  THEN B_DECILE_BOOKED_F = 8;
			ELSE IF int(NOTA) <7640  THEN B_DECILE_BOOKED_F = 9;
			ELSE IF int(NOTA) <100000   THEN B_DECILE_BOOKED_F = 10;
		END;

	ELSE IF B_business_name = 'SQE used for granting CMC' THEN
		DO;
			IF int(NOTA) = . 		  	THEN B_DECILE_DEMAND = .;
			ELSE IF int(NOTA) <3374  THEN B_DECILE_DEMAND = 1;
			ELSE IF int(NOTA) <4007  THEN B_DECILE_DEMAND = 2;
			ELSE IF int(NOTA) <4364  THEN B_DECILE_DEMAND = 3;
			ELSE IF int(NOTA) <4609  THEN B_DECILE_DEMAND = 4;
			ELSE IF int(NOTA) <4828  THEN B_DECILE_DEMAND = 5;
			ELSE IF int(NOTA) <5039  THEN B_DECILE_DEMAND = 6;
			ELSE IF int(NOTA) <5275  THEN B_DECILE_DEMAND = 7;
			ELSE IF int(NOTA) <5619  THEN B_DECILE_DEMAND = 8;
			ELSE IF int(NOTA) <6210  THEN B_DECILE_DEMAND = 9;
			ELSE IF int(NOTA) <100000   THEN B_DECILE_DEMAND = 10;

			IF int(NOTA) = . 		 THEN B_DECILE_BOOKED_F = .;
			ELSE IF int(NOTA) <4139  THEN B_DECILE_BOOKED_F = 1;
			ELSE IF int(NOTA) <4454  THEN B_DECILE_BOOKED_F = 2;
			ELSE IF int(NOTA) <4721  THEN B_DECILE_BOOKED_F = 3;
			ELSE IF int(NOTA) <4952  THEN B_DECILE_BOOKED_F = 4;
			ELSE IF int(NOTA) <5110  THEN B_DECILE_BOOKED_F = 5;
			ELSE IF int(NOTA) <5316  THEN B_DECILE_BOOKED_F = 6;
			ELSE IF int(NOTA) <5578  THEN B_DECILE_BOOKED_F = 7;
			ELSE IF int(NOTA) <5884  THEN B_DECILE_BOOKED_F = 8;
			ELSE IF int(NOTA) <6653  THEN B_DECILE_BOOKED_F = 9;
			ELSE IF int(NOTA) <100000   THEN B_DECILE_BOOKED_F = 10;
		END;

	if f_business_name = 'Fraud score Spain distribution Cetelem' then
		do;
			fraud_score_P1 = ZFRAUDSCR/1E16;
			fraud_score_P0 = 1-fraud_score_P1;

			IF 		fraud_score_P0 = . 		   			THEN F_DECILE_DEMAND = .;
			ELSE IF fraud_score_P0 <  0.9810057986		THEN F_DECILE_DEMAND = 1;
			ELSE IF fraud_score_P0 <  0.9905172679		THEN F_DECILE_DEMAND = 2;
			ELSE IF fraud_score_P0 <  0.9943031893		THEN F_DECILE_DEMAND = 3;
			ELSE IF fraud_score_P0 <  0.9963686950		THEN F_DECILE_DEMAND = 4;
			ELSE IF fraud_score_P0 <  0.9976316950 		THEN F_DECILE_DEMAND = 5;
			ELSE IF fraud_score_P0 <  0.9984584643		THEN F_DECILE_DEMAND = 6;
			ELSE IF fraud_score_P0 <  0.9990010295		THEN F_DECILE_DEMAND = 7;
			ELSE IF fraud_score_P0 <  0.9993776147		THEN F_DECILE_DEMAND = 8;
			ELSE IF fraud_score_P0 <  0.9996655407		THEN F_DECILE_DEMAND = 9;
			ELSE IF fraud_score_P0 <= 1		 	    	THEN F_DECILE_DEMAND = 10;	

			IF 		fraud_score_P0 = . 		   			THEN F_DECILE_BOOKED_F = .;
			ELSE IF fraud_score_P0 < 0.9929208313		THEN F_DECILE_BOOKED_F = 1;
			ELSE IF fraud_score_P0 < 0.9966952829		THEN F_DECILE_BOOKED_F = 2;
			ELSE IF fraud_score_P0 < 0.9979780297	  	THEN F_DECILE_BOOKED_F = 3;
			ELSE IF fraud_score_P0 < 0.9986226124		THEN F_DECILE_BOOKED_F = 4;
			ELSE IF fraud_score_P0 < 0.9990114033		THEN F_DECILE_BOOKED_F = 5;
			ELSE IF fraud_score_P0 < 0.9992783451		THEN F_DECILE_BOOKED_F = 6;
			ELSE IF fraud_score_P0 < 0.9994815525		THEN F_DECILE_BOOKED_F = 7;
			ELSE IF fraud_score_P0 < 0.9996470531		THEN F_DECILE_BOOKED_F = 8;
			ELSE IF fraud_score_P0 < 0.9997944619	 	THEN F_DECILE_BOOKED_F = 9;
			ELSE IF fraud_score_P0 <=1 					THEN F_DECILE_BOOKED_F = 10;	
		end;

		if a_business_name = 'ORANGE APPLICATION PERSONAL JAZZTEL' then
			do;
				if zxnota = '' 							THEN F_DECILE_DEMAND = .;
				else if zxnota lt 535 					THEN F_DECILE_DEMAND = 1; 
				else if zxnota le 561 					THEN F_DECILE_DEMAND = 2; 
				else if zxnota le 578 					THEN F_DECILE_DEMAND = 3; 
				else if zxnota le 593 					THEN F_DECILE_DEMAND = 4; 
				else if zxnota le 609 					THEN F_DECILE_DEMAND = 5; 
				else if zxnota le 624 					THEN F_DECILE_DEMAND = 6; 
				else if zxnota le 638 					THEN F_DECILE_DEMAND = 7; 
				else if zxnota le 652 					THEN F_DECILE_DEMAND = 8; 
				else if zxnota le 664 					THEN F_DECILE_DEMAND = 9; 
				else if zxnota le 999 					THEN F_DECILE_DEMAND = 10; 

				if zxnota = '' 							THEN F_DECILE_BOOKED_F = .;
				else if zxnota lt 535 					THEN F_DECILE_BOOKED_F = 1; 
				else if zxnota le 561 					THEN F_DECILE_BOOKED_F = 2; 
				else if zxnota le 578 					THEN F_DECILE_BOOKED_F = 3; 
				else if zxnota le 593 					THEN F_DECILE_BOOKED_F = 4; 
				else if zxnota le 609 					THEN F_DECILE_BOOKED_F = 5; 
				else if zxnota le 624 					THEN F_DECILE_BOOKED_F = 6; 
				else if zxnota le 638 					THEN F_DECILE_BOOKED_F = 7; 
				else if zxnota le 652 					THEN F_DECILE_BOOKED_F = 8; 
				else if zxnota le 664 					THEN F_DECILE_BOOKED_F = 9; 
				else if zxnota le 999 					THEN F_DECILE_BOOKED_F = 10; 
			end;

		else if a_business_name = 'ORANGE APPLICATION BUSINESS' then
			do;
				if zxnota = '' 							THEN F_DECILE_DEMAND = .;
				else if zxnota lt 536 					THEN F_DECILE_DEMAND = 1; 
				else if zxnota le 572 					THEN F_DECILE_DEMAND = 2; 
				else if zxnota le 592 					THEN F_DECILE_DEMAND = 3; 
				else if zxnota le 607 					THEN F_DECILE_DEMAND = 4; 
				else if zxnota le 622 					THEN F_DECILE_DEMAND = 5; 
				else if zxnota le 636 					THEN F_DECILE_DEMAND = 6; 
				else if zxnota le 647 					THEN F_DECILE_DEMAND = 7; 
				else if zxnota le 655 					THEN F_DECILE_DEMAND = 8; 
				else if zxnota le 671 					THEN F_DECILE_DEMAND = 9; 
				else if zxnota le 999 					THEN F_DECILE_DEMAND = 10; 

				if zxnota = '' 							THEN F_DECILE_BOOKED_F = .;
				else if zxnota lt 536 					THEN F_DECILE_BOOKED_F = 1; 
				else if zxnota le 572 					THEN F_DECILE_BOOKED_F = 2; 
				else if zxnota le 592 					THEN F_DECILE_BOOKED_F = 3; 
				else if zxnota le 607 					THEN F_DECILE_BOOKED_F = 4; 
				else if zxnota le 622 					THEN F_DECILE_BOOKED_F = 5; 
				else if zxnota le 636 					THEN F_DECILE_BOOKED_F = 6; 
				else if zxnota le 664 					THEN F_DECILE_BOOKED_F = 7; 
				else if zxnota le 655 					THEN F_DECILE_BOOKED_F = 8; 
				else if zxnota le 671 					THEN F_DECILE_BOOKED_F = 9; 
				else if zxnota le 999 					THEN F_DECILE_BOOKED_F = 10; 
			end;

		else if a_business_name = 'ORANGE APPLICATION PERSONAL PORTABILITY' then
			do;
				if zxnota = '' 							THEN F_DECILE_DEMAND = .;
				else if zxnota lt 487 					THEN F_DECILE_DEMAND = 1; 
				else if zxnota le 519 					THEN F_DECILE_DEMAND = 2; 
				else if zxnota le 546 					THEN F_DECILE_DEMAND = 3; 
				else if zxnota le 565 					THEN F_DECILE_DEMAND = 4; 
				else if zxnota le 580 					THEN F_DECILE_DEMAND = 5; 
				else if zxnota le 593 					THEN F_DECILE_DEMAND = 6; 
				else if zxnota le 608 					THEN F_DECILE_DEMAND = 7; 
				else if zxnota le 627 					THEN F_DECILE_DEMAND = 8; 
				else if zxnota le 647 					THEN F_DECILE_DEMAND = 9; 
				else if zxnota le 999 					THEN F_DECILE_DEMAND = 10; 

				if zxnota = '' 							THEN F_DECILE_BOOKED_F = .;
				else if zxnota lt 487 					THEN F_DECILE_BOOKED_F = 1; 
				else if zxnota le 519 					THEN F_DECILE_BOOKED_F = 2; 
				else if zxnota le 546 					THEN F_DECILE_BOOKED_F = 3; 
				else if zxnota le 565 					THEN F_DECILE_BOOKED_F = 4; 
				else if zxnota le 550 					THEN F_DECILE_BOOKED_F = 5; 
				else if zxnota le 593 					THEN F_DECILE_BOOKED_F = 6; 
				else if zxnota le 608 					THEN F_DECILE_BOOKED_F = 7; 
				else if zxnota le 627 					THEN F_DECILE_BOOKED_F = 8; 
				else if zxnota le 647 					THEN F_DECILE_BOOKED_F = 9; 
				else if zxnota le 999 					THEN F_DECILE_BOOKED_F = 10; 
			end;

		else if a_business_name = 'ORANGE APPLICATION PERSONAL PORTFOLIO' then
			do;
				if zxnota = '' 							THEN F_DECILE_DEMAND = .;
				else if zxnota lt 534					THEN F_DECILE_DEMAND = 1; 
				else if zxnota le 563 					THEN F_DECILE_DEMAND = 2; 
				else if zxnota le 584 					THEN F_DECILE_DEMAND = 3; 
				else if zxnota le 602 					THEN F_DECILE_DEMAND = 4; 
				else if zxnota le 615 					THEN F_DECILE_DEMAND = 5; 
				else if zxnota le 627 					THEN F_DECILE_DEMAND = 6; 
				else if zxnota le 639 					THEN F_DECILE_DEMAND = 7; 
				else if zxnota le 648 					THEN F_DECILE_DEMAND = 8; 
				else if zxnota le 660 					THEN F_DECILE_DEMAND = 9; 
				else if zxnota le 999 					THEN F_DECILE_DEMAND = 10; 

				if zxnota = '' 							THEN F_DECILE_BOOKED_F = .;
				else if zxnota lt 534 					THEN F_DECILE_BOOKED_F = 1; 
				else if zxnota le 563 					THEN F_DECILE_BOOKED_F = 2; 
				else if zxnota le 584 					THEN F_DECILE_BOOKED_F = 3; 
				else if zxnota le 602 					THEN F_DECILE_BOOKED_F = 4; 
				else if zxnota le 615 					THEN F_DECILE_BOOKED_F = 5; 
				else if zxnota le 627 					THEN F_DECILE_BOOKED_F = 6; 
				else if zxnota le 639 					THEN F_DECILE_BOOKED_F = 7; 
				else if zxnota le 648 					THEN F_DECILE_BOOKED_F = 8; 
				else if zxnota le 660 					THEN F_DECILE_BOOKED_F = 9; 
				else if zxnota le 999 					THEN F_DECILE_BOOKED_F = 10; 
			end;

		else if a_business_name = 'ORANGE APPLICATION NEW BUSINESS' then
			do;
				if zxnota = '' 							THEN F_DECILE_DEMAND = .;
				else if zxnota lt 533					THEN F_DECILE_DEMAND = 1; 
				else if zxnota le 545					THEN F_DECILE_DEMAND = 2; 
				else if zxnota le 553 					THEN F_DECILE_DEMAND = 3; 
				else if zxnota le 562 					THEN F_DECILE_DEMAND = 4; 
				else if zxnota le 571 					THEN F_DECILE_DEMAND = 5; 
				else if zxnota le 581 					THEN F_DECILE_DEMAND = 6; 
				else if zxnota le 594 					THEN F_DECILE_DEMAND = 7; 
				else if zxnota le 606 					THEN F_DECILE_DEMAND = 8; 
				else if zxnota le 622 					THEN F_DECILE_DEMAND = 9; 
				else if zxnota le 999 					THEN F_DECILE_DEMAND = 10; 

				if zxnota = '' 							THEN F_DECILE_BOOKED_F = .;
				else if zxnota lt 533 					THEN F_DECILE_BOOKED_F = 1; 
				else if zxnota le 545 					THEN F_DECILE_BOOKED_F = 2; 
				else if zxnota le 553 					THEN F_DECILE_BOOKED_F = 3; 
				else if zxnota le 562 					THEN F_DECILE_BOOKED_F = 4; 
				else if zxnota le 571 					THEN F_DECILE_BOOKED_F = 5; 
				else if zxnota le 581 					THEN F_DECILE_BOOKED_F = 6; 
				else if zxnota le 594 					THEN F_DECILE_BOOKED_F = 7; 
				else if zxnota le 606 					THEN F_DECILE_BOOKED_F = 8; 
				else if zxnota le 622 					THEN F_DECILE_BOOKED_F = 9; 
				else if zxnota le 999 					THEN F_DECILE_BOOKED_F = 10; 
			end;
    output sm_tmp.demand_prf_char;
    output sm_tmp.sm_score_lookup_input;
    output sm_tmp.sm_app_index;
run;


%sm_check_step(Scoring and fixed deciles);
%sm_assert_unique(data=sm_tmp.sm_app_index, keys=company authorization_id,
                  out=sm_tmp.qa_scoring_duplicates);
