/* Run from the repository directory, or set sm_code_dir to its server path.
   Example overrides before including this file:
     %let sm_code_dir=/risk/actual/score_monitoring/code;
     %let sm_start_stage=12;
     %let sm_end_stage=20;
     %let sm_full_report=Y;   * first run without a report backup;
   For isolated validation, assign libraries yourself and set sm_setup=N. */
%macro sm_bootstrap;
    %if not %symexist(sm_code_dir) %then %do;
        %global sm_code_dir; %let sm_code_dir=.;
    %end;
%mend;
%sm_bootstrap;
%include "&sm_code_dir./macros/validation.sas";
%sm_default(sm_setup, Y);
%sm_default(sm_start_stage, 1);
%sm_default(sm_end_stage, 20);
%macro sm_initialize;
    %if %upcase(&sm_setup)=Y %then %include "&sm_code_dir./00_SETUP.sas";
%mend;
%sm_initialize;
%include "&sm_code_dir./macros/kpi.sas";
%include "&sm_code_dir./macros/harmonized_performance.sas";
%include "&sm_code_dir./macros/output_columns.sas";
%include "&sm_code_dir./02_SCORE_MODELS.sas";
options fullstimer msglevel=i;

%macro sm_stage(number, file);
    %if &number >= &sm_start_stage and &number <= &sm_end_stage %then %do;
        %put NOTE: SM_STAGE_BEGIN &file;
        %include "&sm_code_dir./&file";
        %sm_check_step(&file);
        %put NOTE: SM_STAGE_END &file;
    %end;
%mend;
%sm_stage(1,01_BACKUP.sas);
%sm_stage(3,03_NDD_DATA.sas);
%sm_stage(4,04A_CET_TPT.sas);
%sm_stage(4,04B_CMC_TPT.sas);
%sm_stage(4,04C_XFR_TPT.sas);
%sm_stage(4,04D_OSP_TPT.sas);
%sm_stage(5,05A_CET_NDD.sas);
%sm_stage(5,05B_CMC_NDD.sas);
%sm_stage(5,05C_XFR_NDD.sas);
%sm_stage(5,05D_OSS_NDD.sas);
%sm_stage(6,06A_CET_MOUCHARD.sas);
%sm_stage(6,06B_CMC_MOUCHARD.sas);
%sm_stage(6,06C_XFR_MOUCHARD.sas);
%sm_stage(6,06D_OPS_IC3.sas);
%sm_stage(7,07A_CET_STATIC_INFO.sas);
%sm_stage(7,07B_CMC_STATIC_INFO.sas);
%sm_stage(7,07C_XFR_STATIC_INFO.sas);
%sm_stage(7,07D_OSP_STATIC_INFO.sas);
%sm_stage(8,08A_CET_JOIN_STATIC_MOUCHARDS.sas);
%sm_stage(8,08B_CMC_JOIN_STATIC_MOUCHARD.sas);
%sm_stage(8,08C_XFR_JOIN_STATIC_MOUCHARD.sas);
%sm_stage(8,08D_OSP_JOIN_STATIC_IC3.sas);
%sm_stage(9,09A_CET_SQE_INFO.sas);
%sm_stage(9,09B_CMC_SQE_INFO.sas);
%sm_stage(9,09C_XFR_SQE_INFO.sas);
%sm_stage(9,09D_OSP_SQE_INFO.sas);
%sm_stage(10,10A_CET_UPDATE.sas);
%sm_stage(10,10B_CET_UPDATE.sas);
%sm_stage(10,10C_XFR_UPDATE.sas);
%sm_stage(10,10D_OSP_UPDATE.sas);
%sm_stage(11,11A_CET_KPI.sas);
%sm_stage(11,11B_CMC_KPI.sas);
%sm_stage(11,11C_XFR_KPI.sas);
%sm_stage(11,11D_OSP_KPI.sas);
%sm_stage(12,12_JOIN.sas);
%sm_stage(13,13_SCORECARDS.sas);
%sm_stage(14,14_CHAR_ANALYSIS.sas);
%sm_stage(15,15_DECILES.sas);
%sm_stage(16,16_RISK_LEVELS.sas);
%sm_stage(17,17_BAD_RATE.sas);
%sm_stage(18,18_OUTPUT.sas);
%sm_stage(19,19_CPCR.sas);
%sm_stage(20,20_CUTTOFFS.sas);
