/* Actual step 12: overlapping account AND authorization numbers across brands. */
data sm_tmp.sm_demand_ctlm_END_U;
    authorization_id=1; account_id=99; mis_date='01JAN2024'd;
    status_name='Booked'; output;
    authorization_id=2; account_id=.; status_name='Cancel'; output;
run;
data sm_tmp.sm_demand_cmc_END_U;
    authorization_id=1; account_id=99; mis_date='01JAN2024'd; status_name='Booked';
run;
data sm_tmp.sm_demand_xfr_END_U sm_tmp.sm_demand_osp_END_U;
    if 0 then set sm_tmp.sm_demand_ctlm_END_U;
    stop;
run;
data sm_tmp.kpi_ctlm sm_tmp.kpi_cmc;
    if 0 then set work.kpi;
    account_id=99; acct_booked_h0=1; acct_booked_h6=1; acct_booked_h12=1;
    company='CETELEM'; todu_h12=100; output sm_tmp.kpi_ctlm;
    company='CMC'; todu_h12=200; output sm_tmp.kpi_cmc;
run;
data sm_tmp.kpi_xfr sm_tmp.kpi_osp;
    if 0 then set work.kpi;
    stop;
run;
%include "&sm_code_dir./12_JOIN.sas";
%expect_equal(%sm_nobs(sm_tmp.demand_prf),3,Actual KPI join preserves application grain);
data work.application_join_failures;
    set sm_tmp.demand_prf;
    if company='CETELEM' and account_id=99 and todu_h12 ne 100 then output;
    if company='CMC' and account_id=99 and todu_h12 ne 200 then output;
    if authorization_id=2 and (sm_kpi_match ne 0 or not missing(todu_h12)) then output;
run;
%expect_equal(%sm_nobs(work.application_join_failures),0,KPI join separates companies and missing account);
